Repository acm-ucr/rishi-website, pull requests merged in 2024-03, with the labels that each got.

#115 Added board linkedin and removed mail icon
  src/components/board/Board.jsx
  src/components/board/Member.jsx
  src/data/staff.js
Labels: ready for review 📝, Board

#159 Hover Animation on Footer
  src/components/Footer.jsx
Labels: ready for review 📝

#161 added framer to last 3 components
  src/app/page.js
Labels: ready to merge 🔥

#156 removed shadow from icons and border has hover animation
  src/components/home/Socials.jsx
Labels: ready for review 📝, Events

#158 nav issue
  src/app/gallery/[trip]/page.js
  src/app/layout.js
  src/data/navigation.js
Labels: ready for review 📝

#152 Added breakpoints for smaller screens
  src/components/home/Landing.jsx
Labels: ready for review 📝, Development

#171 adding hover animation
  src/components/Footer.jsx
  src/components/board/Member.jsx
Labels: ready to merge 🔥

#172 Added hover animation
  src/components/gallery/Options.jsx
Labels: ready for review 📝, Development

#168 google calendar api
  package-lock.json
  package.json
  src/components/events/Calendar.jsx
  src/components/events/CalendarApi.jsx
Labels: ready for review 📝
