Repository acm-ucr/rishi-website, pull requests merged in 2024-02, with the labels that each got.

#98 fixed landing bug
  src/app/gallery/[trip]/page.js
  src/components/home/Landing.jsx
Labels: ready for review 📝

#99 Optimized for mobile responsiveness
  src/components/about/About.jsx
Labels: ready for review 📝

#108 404 Page Updated
  src/app/not-found.js
Labels: ready for review 📝

#110 Added Footer Links
  src/components/Footer.jsx
Labels: ready for review 📝, Navigation

#100 Gallery Button Font/Spacing Fixes
  src/components/gallery/Options.jsx
Labels: ready for review 📝, Gallery

#109 Populate Board Data
  src/components/board/Board.jsx
  src/components/board/Member.jsx
  src/data/staff.js
Labels: ready for review 📝, Board, Development

#113 Button-Fixes
  src/components/Button.jsx
Labels: ready for review 📝

#114 Mobile Responsiveness
  src/components/home/Mission.jsx
Labels: ready for review 📝, Responsiveness

#117 deleted the two sets of dup photos in india2014
  src/data/gallery.js
Labels: ready to merge 🔥, ready for review 📝

#116 Updated carousel.jsx images
  public/carousel/rishi_event_1.webp
  public/carousel/rishi_event_2.webp
  public/carousel/rishi_event_3.webp
  public/carousel/rishi_event_4.webp
  public/carousel/rishi_event_5.webp
  public/carousel/rishi_event_6.webp
  src/data/carousel.js
Labels: ready for review 📝

#119 Added Toolbar for mobile and made calendar visible on small screens
  src/components/events/Calendar.jsx
  src/components/events/ToolBar.jsx
Labels: ready for review 📝, Responsiveness

#118 landing pic breakpoint
  src/components/home/Landing.jsx
Labels: ready for review 📝

#122 navbar changes
  src/components/Navigation.jsx
  src/components/events/Calendar.jsx
  src/components/events/ToolBar.jsx
Labels: ready for review 📝

#128 fix board sizing
  public/trips/pad2022/pad_28 copy.jpg
  src/components/board/Member.jsx
Labels: ready for review 📝, Board

#138 Socials - Mobile Responsiveness (updated)
  src/components/home/Socials.jsx
Labels: ready for review 📝, Responsiveness

#140 Added white spacing
  src/app/about/page.js
  src/app/board/page.js
  src/app/gallery/page.js
Labels: ready to merge 🔥, ready for review 📝, Development

#141 Restored Color to Orange
  src/components/Button.jsx
Labels: ready for review 📝

#145 removed underlines and changed blue icons to white
  src/components/Footer.jsx
  src/components/home/Socials.jsx
Labels: ready for review 📝, Home

#144 gallery fixes
  src/components/gallery/GalleryImage.jsx
Labels: ready for review 📝

#139 Ialib001/similar gallery
  src/data/gallery.js
Labels: ready for review 📝
