Repository acm-ucr/rishi-website, pull requests merged in 2024-01, with the labels that each got.

#25 created divider
  src/components/home/Divider.jsx
Labels: ready for review 📝

#19 social jsx
  src/components/home/Socials.jsx
Labels: ready for review 📝

#42 Gallery - Options
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/gallery/Options.jsx
Labels: ready for review 📝, Gallery

#28 Options - Gallery
  src/components/gallery/Options.jsx
Labels: do not merge ❌, Gallery

#37 Gallery - Options
  package-lock.json
  package.json
  src/app/page.js
  src/components/Button.jsx
  src/components/gallery/Options.jsx
Labels: ready for review 📝, Gallery

#30 Member Card created
  src/components/board/Member.jsx
Labels: ready for review 📝

#35 Mission-Home
  package-lock.json
  package.json
  src/components/home/Mission.jsx
Labels: ready for review 📝

#18 Made heading component
  src/app/about/page.js
  src/app/board/page.js
  src/app/gallery/page.js
  src/app/page.js
  src/components/Heading.jsx
Labels: ready for review 📝

#34 created landing page and altered button component
  src/components/Button.jsx
  src/components/home/Landing.jsx
Labels: help wanted, ready for review 📝

#51 created image data
  src/app/not-found.js
  src/app/page.js
  src/components/about/About.jsx
  src/data/gallery.js
Labels: do not merge ❌

#26 Footer
  src/components/Footer.jsx
  src/components/about/About.jsx
Labels: ready for review 📝, Navigation

#33 outlook
  package-lock.json
  package.json
  src/app/events/page.js
  src/components/events/Calendar.jsx
  src/components/events/ToolBar.jsx
  src/components/events/modal.jsx
  src/components/events/rbc.css
Labels: ready for review 📝

#55 Set up the grid for member component
  src/components/board/Board.jsx
  src/data/staff.js
Labels: ready for review 📝, Development

#38 finished nav bar
  package-lock.json
  package.json
  src/components/Navigation.jsx
  src/data/navigation.js
Labels: help wanted, Navigation

#93 created carousel
  src/app/page.js
  src/components/home/Carousel.jsx
  src/data/carousel.js
  tailwind.config.js
Labels: ready for review 📝
